name: Espresso test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Start Android emulator
      uses: reactivecircus/android-emulator-runner@v2
    - name: Run Espresso tests
      run: |
        ./gradlew connectedCheck --stacktrace
      env:
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
        JAVA_HOME: ${{ env.JAVA_HOME }}
